{% set name = "standardiser" %}
{% set version = "0.1.9" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 611f520b999058026380b506da593e072f566d351e68e4cd1d8f7e8cd7728c82

build:
  noarch: python
  number: 0
  entry_points:
    - standardise-mols=standardiser.bin.standardise_mols:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python
    - rdkit

test:
  imports:
    - standardiser
    - standardiser.bin
  commands:
    - standardise-mols --help

about:
  home: https://www.ebi.ac.uk/chembldb/index.php/ws
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Provides a simple way of standardising molecules as a prelude to e.g. molecular modelling exercises. 
  dev_url: https://github.com/flatkinson/standardiser

extra:
  recipe-maintainers:
    - tsenapathi
    - simonbray
