travis:
  secure:
    BINSTAR_TOKEN: wIMA9LfqPVrl7cff5WR1Cc0Ny/XkM9jTzKBO45shS85ogTfqKCxmCTiiDgNobF1pMMCW7v6KMrQl0/QQnn+SznJQMU6Lwpf10hFQWSWfIixz3BAxsWtRkgdV4JFp1iCRd+cpmYTz/+86JCB9TgzrSUn97AO0PmRoiV/jpxA0nOdfKP+QK2ggXJBmsHN1cu9ceicoYiTCVaYyOoo6FViiRIz6qZahX7aAYvU6hpj4wtbtvz8IK8dtrmdQLgIbhodkKO7Ud7Rmf5ZkwuhqsRDb76oJmLhvK4zp6tPjcwSKaWTIhYAdIescYepo9j6ZsyEhr/TEZiLGxx4mq8VdZ+1eVb2Sg7k58LoFldYHjEMuJMPulgT+Rg0/t8Z6KvXKcc2zXTYrfmTjciStwTXleEfld05fkTS8AJDIAXAN7qGvBfEjG+U+vJyFF+ElVhXGZCFjtjTW+brl3YfoCx+g/myY7R1tx3BIjwL94eu7pkad61tRBqCZDzF7Uu9VkeP6Aq8FZ2deROONDy2n3PVGnI0fUriXnFIhEjDDrpphL58cWT/75KvL5wW+sZbm4eCBhHNOKBEppJp9qQG9okcHtPFpcSd05o0/XyZGffUplF1WDe3ARayCbP19OnNXdq2GKQ8oVdb1co4GzrJgcfjiHCRhg2qcUECRdL6SqCUS00gRRWs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
